web/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using domaine.entities;
using Newtonsoft.Json;
using SpecificServices.services;
using web.Util;

namespace web.Controllers
{
    public class CartController : Controller
    {
        [HttpPost]
        public string Add(int id)
        {
            ProductService productService = new ProductService();
            product product = productService.GetById(id);
            if (product != null)
            {


                Dictionary<product, int> cart = (Dictionary<product, int>) Session["cart"];
                if (cart == null)
                    cart = new Dictionary<product, int>();

                if (cart.ContainsKey(product))
                {
                    cart[product]++;
                }

                else
                {
                    cart[product] = 1;
                }

                Session["cart"] = cart;

              
                 
              
               
                
                
                return JsonConvert.SerializeObject(new MessageResponse {Code=0,Message = "Product added to cart" });
                //return JsonConvert.SerializeObject(cart);
            }

            return JsonConvert.SerializeObject(new MessageResponse {Code = 1,Message = "Couldn't add product to card"});

        }

        public string Count()
        {
            Dictionary<product,int> cart = (Dictionary<product, int>) Session["cart"];
            if (cart == null)
            {
                return "0";
            }
            else
            {
                return cart.Count.ToString();
            }
        }

        public ActionResult Content()
        {
            Dictionary<product, int> cart = (Dictionary<product, int>)Session["cart"];
            ViewBag.cart = cart;
            return PartialView();
        }
    }

  
}

web/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls.Expressions;
using domaine.entities;
using SkiingTheWorld_PI.Domaine.Entities;
using SpecificServices.services;

namespace web.Controllers
{
    public class ShopController : Controller
    {
        // GET: Shop
        public ActionResult Index()
        {
            SousCategorieService sousCategorieService = new SousCategorieService();
            return View(sousCategorieService.GetAll());
        }

        [Route("SubCategory")]
        public ActionResult SubCategory(int cat,int scat)
        {
            ProductService s = new ProductService();
            SousCategorieService sousCategorieService = new SousCategorieService();

            ViewBag.sCats = sousCategorieService.GetAll().Where(sc => ((int)sc.MarquecategorieProd) == cat).ToList();

            List<product> p = new List<product>();

            foreach (product product in s.GetAll())
            {
                
                
                if (product.sousCategorieProd.Equals(sousCategorieService.GetById(scat)) &&
                   ((int) product.sousCategorieProd.MarquecategorieProd) == cat)
                {
                    p.Add(product);
                }
            }

            return View(p);
        }

        [Route("Category")]
        public ActionResult Category(int cat)
        {


            SousCategorieService sousCategorieService = new SousCategorieService();
            ViewBag.sCats = sousCategorieService.GetAll().Where(sc=> ((int)sc.MarquecategorieProd) == cat).ToList();

            ProductService s = new ProductService();

            List<product> p = new List<product>();

            foreach (product product in s.GetAll())
            {

                if (
                    ((int)product.sousCategorieProd.MarquecategorieProd) == cat)
                {
                    p.Add(product);
                }
            }
            return View(p);
        }

        public ActionResult Product(int id)
        {
            ProductService ps = new ProductService();
            product p = ps.GetById(id);
            if (p == null)
                return new HttpNotFoundResult();
            List<product> others = new List<product>();



            do
            {
                int index = new Random().Next(1, ps.GetAll().Count());
                System.Diagnostics.Debug.WriteLine(ps.GetAll().Count());
                product toAdd = ps.GetAll().ToList()[index];
                if (others.Where(pro => pro.Reference == toAdd.Reference && pro.Reference != id).Count() == 0)
                {
                    others.Add(toAdd);
                }
               
            } while (others.Count != 3);
            

            ViewBag.others = others;
           
            return View(p);
        }

         [HttpPost]
        public ActionResult RenderProducts(int? cat,int? scat,String search)
            {

                ProductService s = new ProductService();
                List<product> products = s.GetAll().ToList();

                if (scat == null)
                {
                    products = products.Where(p => ((int) p.sousCategorieProd.MarquecategorieProd) == cat)
                        .ToList();
                }

            if(scat != null && cat != null)
                {
                products = products.Where(p => ((int)p.sousCategorieProd.MarquecategorieProd) == cat && p.sousCategorieProd.Id == scat)
                    .ToList();
            }

                if (search != null)
                {
                    products = products.Where(p => p.Description.ToLower().Contains(search.ToLower()) || p.Name.ToLower().Contains(search.ToLower())).ToList();
                }

                ViewBag.products = products;

                return PartialView();
            }
        
    }
}

web/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using domaine.entities;
using Newtonsoft.Json;
using web.App_Start;
using web.Util;

namespace web.Controllers
{
    public class productsController : Controller
    {
        private SWModel db = new SWModel();

        // GET: products
        public ActionResult Index()
        {
            user u = (user)Session["user"];
            if (u != null)
            {
                if (u.role == "ROLE_AGENT")
                {
                    var product = db.product.Include(p => p.sousCategorieProd);
                    return View(product.ToList().Where(pr=>pr.userId ==u.id));
                }

            }

            return new HttpStatusCodeResult(403);
        }

        // GET: products/Details/5
        public ActionResult Details(int? id)
        {
            user u = (user)Session["user"];
            if (u != null)
            {
                if (u.role == "ROLE_AGENT")
                {

                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    product product = db.product.Find(id);
                    if (product == null)
                    {
                        return HttpNotFound();
                    }
                    return View(product);
                }

            }

            return new HttpStatusCodeResult(403);
        }

        // GET: products/Create
        public ActionResult Create()
        {
            user u = (user) Session["user"];
            if (u != null)
            {
                if (u.role == "ROLE_AGENT")
                {
                    
                    ViewBag.sousCategorieProdId = new SelectList(db.souscategories, "Id", "Libelle");
                    return View();
                }
                
            }

            return new HttpStatusCodeResult(403);
        }

        // POST: products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Reference,Description,Marque,Modele,Name,Photo,Quantity,Color,Size,price,sousCategorieProdId,userId")] product product,HttpPostedFileBase File)
        {



            if (ModelState.IsValid)
            {
                HttpWebRequest request = (HttpWebRequest)WebRequest.Create(Config.URL + "badword");
                request.Method = "POST";
                request.Headers.Add("text", product.Description);
                using (var reader =new StreamReader(request.GetResponse().GetResponseStream(),Encoding.UTF8))
                {
                    string responsetext = reader.ReadToEnd();
                    MessageResponse msg = JsonConvert.DeserializeObject<MessageResponse>(responsetext);
                    if (msg.Code == 0)
                    {
                        if (File.ContentLength > 0)
                        {
                            string _FileName = Path.GetFileName(new Random().Next().ToString() + File.FileName);
                            var path = Path.Combine(Server.MapPath("~/Content/Upload"), _FileName);

                            File.SaveAs(path);
                            product.Photo= _FileName;
                        }
                        user u = (user)Session["user"];
                        product.userId = u.id;
                        db.product.Add(product);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        
                        List<string> badworsList =JsonConvert.DeserializeObject <List<string>>(msg.Message.ToString());
                     

                        return RedirectToAction("Create",new {msg=JsonConvert.SerializeObject(badworsList)});
                    }
                }

                
            }

            ViewBag.sousCategorieProdId = new SelectList(db.souscategories, "Id", "Libelle", product.sousCategorieProdId);
            return View(product);
        }

        // GET: products/Edit/5
        public ActionResult Edit(int? id)
        {
            user u = (user)Session["user"];
            if (u != null)
            {
                if (u.role == "ROLE_AGENT")
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    product product = db.product.Find(id);
                    if (product == null)
                    {
                        return HttpNotFound();
                    }
                    ViewBag.sousCategorieProdId = new SelectList(db.souscategories, "Id", "Libelle", product.sousCategorieProdId);
                    return View(product);
                }

            }

            return new HttpStatusCodeResult(403);
        }

        // POST: products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Reference,MarquecategorieProd,Description,Marque,Modele,Name,Photo,Quantity,Color,Size,price,sousCategorieProdId,userId")] product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.sousCategorieProdId = new SelectList(db.souscategories, "Id", "Libelle", product.sousCategorieProdId);
            return View(product);
        }

        // GET: products/Delete/5
        public ActionResult Delete(int? id)
        {
            user u = (user)Session["user"];
            if (u != null)
            {
                if (u.role == "ROLE_AGENT")
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    product product = db.product.Find(id);
                    if (product == null)
                    {
                        return HttpNotFound();
                    }
                    return View(product);

                }

            }

            return new HttpStatusCodeResult(403);
        }

        // POST: products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            product product = db.product.Find(id);
            db.product.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

web/Views/Shop/Category.cshtml
@using System.Net.Cache
@using System.Net.Configuration
@using domaine.entities
@using SkiingTheWorld_PI.Domaine.Entities
@{
    ViewBag.Title = "Category";
    Layout = "~/Views/Shared/_Home.cshtml";
}

<!-- BREADCRUMBS -->
<section class="breadcrumb ski parallax margbot50">

    <!-- CONTAINER -->
    <div class="container">
        <h2>Women</h2>
    </div><!-- //CONTAINER -->
</section><!-- //BREADCRUMBS -->
<!-- SHOP BLOCK -->
<section class="shop" style="padding-top: 2%">

    <!-- CONTAINER -->
    <div class="container">

        <!-- ROW -->
        <div class="row">

            <!-- SIDEBAR -->
            <div id="sidebar" class="col-lg-3 col-md-3 col-sm-3 padbot50">
                <div class="sidepanel widget_search">
                    <form class="search_form" action="javascript:void(0);" method="get" name="search_form">
                        <input id="search_input" type="text" name="Search..." value="Search..." onfocus="if (this.value == 'Search...') this.value = '';" onblur="if (this.value == '') this.value = 'Search...';">
                    </form>
                </div>

                <!-- CATEGORIES -->
                <div class="sidepanel widget_categories">
                    <h3>Product Categories</h3>
                    <ul>

                        @foreach (souscategorie sc in ((List<souscategorie>) ViewBag.sCats))
                        {
                            <li><a href="@Url.Action("SubCategory", new {cat = @Request.QueryString["cat"], scat = @sc.Id})">@sc.Libelle</a></li>
                        }

                    </ul>
                </div><!-- //CATEGORIES -->

            </div><!-- //SIDEBAR -->
            <!-- SHOP PRODUCTS -->
            <div class="col-lg-9 col-sm-9 col-sm-9 padbot20">



                <!-- SORTING TOVAR PANEL -->
                <div class="sorting_options clearfix">

                    <!-- COUNT TOVAR ITEMS -->
                    <div class="count_tovar_items">
                        <p>Sweaters</p>
                        <span>@Html.Raw(Model.Count)</span>
                    </div><!-- //COUNT TOVAR ITEMS -->
                    
                    <!-- PRODUC SIZE -->
                    <div id="toggle-sizes">
                        <a class="view_box active" href="javascript:void(0);"><i class="fa fa-th-large"></i></a>
                        <a class="view_full" href="javascript:void(0);"><i class="fa fa-th-list"></i></a>
                    </div><!-- //PRODUC SIZE -->
                </div><!-- //SORTING TOVAR PANEL -->
                <!-- ROW -->
                <div class="row shop_block" id="product_container">

                   

                </div><!-- //ROW -->

                <hr>

                <div class="clearfix">
                    

                    <a class="show_all_tovar" href="javascript:void(0);">show all</a>

                </div>

            </div><!-- //SHOP PRODUCTS -->
        </div><!-- //ROW -->
    </div><!-- //CONTAINER -->
</section><!-- //SHOP -->

@section scripts
{
    <script>

        
        $.ajax({
            url: '@Url.Action("RenderProducts", "Shop")',
            type: 'POST',
            data: {
                cat:'@Request.Params["cat"]'
            },
            success:function(data) {
                $('#product_container').html(data);
            }
        });

        $('#search_input').change(function () {
            $(this).focusout();
            $.ajax({
                url: '@Url.Action("RenderProducts", "Shop")',
                type: 'POST',
                data: {
                    cat: '@Request.Params["cat"]',
                    search:$('#search_input').val()
                },
                success: function (data) {
                    $('#product_container').html(data);
                }
            });
        });
    </script>
}

web/Views/Shop/Product.cshtml
@using domaine.entities
@model domaine.entities.product
@{
    ViewBag.Title = "Product";
    Layout = "~/Views/Shared/_Home.cshtml";
}

@section css
{
    
<link href="~/Content/css/toastr.min.css" rel="stylesheet" />
}

<!-- BREADCRUMBS -->
<section class="breadcrumb parallax margbot30"></section>
<!-- //BREADCRUMBS -->
<!-- TOVAR DETAILS -->
<section class="tovar_details padbot70">

    <!-- CONTAINER -->
    <div class="container">

        <!-- ROW -->
        <div class="row">

            <!-- SIDEBAR TOVAR DETAILS -->
            <div class="col-lg-3 col-md-3 sidebar_tovar_details">
                <h3><b>other products</b></h3>

                <ul class="tovar_items_small clearfix">
                    @foreach (product item in ((List<product>) ViewBag.others))
                    {
                        <li class="clearfix">
                            <img class="tovar_item_small_img" src="@Url.Content("~/Content/Upload/")@Html.DisplayFor(modelItem=>item.Photo)" alt=""/>
                            <a href="@Url.Action("Product",new {id=item.Reference})" class="tovar_item_small_title">@Html.Raw(item.Name)</a>
                            <span class="tovar_item_small_price">@Html.Raw(item.price)</span>
                        </li>
                    }
                    
                    
                </ul>
            </div><!-- //SIDEBAR TOVAR DETAILS -->
            <!-- TOVAR DETAILS WRAPPER -->
            <div class="col-lg-9 col-md-9 tovar_details_wrapper clearfix">
                <div class="tovar_details_header clearfix margbot35">
                    <h3 class="pull-left"><b>@Html.Raw(Model.sousCategorieProd.Libelle)</b></h3>

                    
                </div>

                <!-- CLEARFIX -->
                <div class="clearfix padbot40">
                    <div class="tovar_view_fotos clearfix">
                        <div id="slider2" class="flexslider">
                            <ul class="slides">
                                <li><a href="javascript:void(0);"><img src="@Url.Content("~/Content/Upload/")@Html.DisplayFor(modelItem=>Model.Photo)" alt="" /></a></li>
                            </ul>
                        </div>

                    </div>

                    <div class="tovar_view_description">
                        <div class="tovar_view_title">@Html.Raw(Model.Name)</div>
                        <div class="tovar_article">Ref : @Html.Raw(Model.Reference)</div>
                        <div class="clearfix tovar_brend_price">
                            <div class="pull-left tovar_brend">@Html.Raw(Model.Modele) - @Html.Raw(Model.Modele)</div>
                            <div class="pull-right tovar_view_price">Dt @Html.Raw(Model.price)</div>
                        </div>
                        <div class="tovar_color_select">
                            <p>Color</p>
                            <a style="background-color: @Html.Raw(Model.Color)" href="javascript:void(0);"></a>
                        </div>
                        <div class="tovar_size_select">
                            <div class="clearfix">
                                <p class="pull-left">SIZE</p>
                            </div>
                            <a class="sizeXS" href="javascript:void(0);">@Html.Raw(Model.Size)</a>
                        </div>
                        <div class="tovar_view_btn">
                            
                            
                            

                            @if (Model.Quantity == 0)
                            {
                                <a disabled class="add_bag btn inactive" href="javascript:void(0);"><i class="fa fa-shopping-cart"></i>Sold out !</a>

                            }
                            else
                            {
                                <a onclick="addToCart(@Html.Raw(Model.Reference))" id="addToCat"class="add_bag btn inactive" href="javascript:void(0);"><i class="fa fa-shopping-cart"></i>Add to bag</a>

                            }
                        </div>

                    </div>
                </div><!-- //CLEARFIX -->
                <!-- TOVAR INFORMATION -->
                <div class="tovar_information">
                    <ul class="tabs clearfix">
                        <li class="current">Details</li>
                        <li>Reviews (2)</li>
                    </ul>
                    <div class="box visible">
                        <p>@Html.Raw(Model.Description)</p>
                    </div>

                    <div class="box">
                        <ul class="comments">
                            <li>
                                <div class="clearfix">
                                    <p class="pull-left"><strong><a href="javascript:void(0);">John Doe</a></strong></p>
                                    <span class="date">2013-10-09 09:23</span>
                                    <div class="pull-right rating-box clearfix">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                    </div>
                                </div>
                                <p>Ut tellus dolor, dapibus eget, elementum vel, cursus eleifend, elit. Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Integer rutrum ante eu lacus.Vestibulum libero nisl, porta vel, scelerisque eget, malesuada at, neque.</p>
                            </li>
                            <li>
                                <div class="clearfix">
                                    <p class="pull-left"><strong><a href="javascript:void(0);">John Doe</a></strong></p>
                                    <span class="date">2013-10-09 09:23</span>
                                    <div class="pull-right rating-box clearfix">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                    </div>
                                </div>
                                <p>Ut tellus dolor, dapibus eget, elementum vel, cursus eleifend, elit. Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Integer rutrum ante eu lacus.Vestibulum libero nisl, porta vel, scelerisque eget, malesuada at, neque.</p>

                                <ul>
                                    <li>
                                        <p><strong><a href="javascript:void(0);">Jane Doe</a></strong></p>
                                        <p>Ut tellus dolor, dapibus eget, elementum vel, cursus eleifend, elit. Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Integer rutrum ante eu lacus.Vestibulum libero nisl, porta vel, scelerisque eget, malesuada at, neque.</p>
                                    </li>
                                </ul>
                            </li>
                        </ul>

                        <h3>WRITE A REVIEW</h3>
                        <p>Now please write a (short) review....(min. 200, max. 2000 characters)</p>
                        <div class="clearfix">
                            <textarea id="review-textarea"></textarea>
                            <label class="pull-left rating-box-label">Your Rate:</label>
                            <div class="pull-left rating-box clearfix">
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                            </div>
                            <input type="submit" class="dark-blue big" value="Submit a review">
                        </div>
                    </div>
                </div><!-- //TOVAR INFORMATION -->
            </div><!-- //TOVAR DETAILS WRAPPER -->
        </div><!-- //ROW -->
    </div><!-- //CONTAINER -->
</section><!-- //TOVAR DETAILS -->

@section scripts
{
    <script src="~/Content/js/toastr.min.js"></script>
<script src="~/Content/js/jquery-ui.js"></script>
    <script>
        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-bottom-full-width",
            "preventDuplicates": true,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }


        function addToCart(productId) {
            $.ajax({
                url:'@Url.Action("Add","Cart")',
                data: {
                    id:productId
                },
                type: 'POST',
                success:function(data) {
                    var response = JSON.parse(data);
                    console.log(response);
                    if (response.Code == 0) {

                        toastr["success"]("Added to cart !");
                        getCartItemsCount();
                        $("#cart").effect("shake");
                        renderCart();

                    } else {
                        toastr["error"](response.Message);
                    }
                }
            });

        };

       
    </script>
}

web/Views/Shop/SubCategory.cshtml
@using domaine.entities
@using SkiingTheWorld_PI.Domaine.Entities


@{
    ViewBag.Title = "SubCategory";
    Layout = "~/Views/Shared/_Home.cshtml";
}


<!-- BREADCRUMBS -->
<section class="breadcrumb ski parallax margbot50">
			
    <!-- CONTAINER -->
    <div class="container">
        <h2>Women</h2>
    </div><!-- //CONTAINER -->
</section><!-- //BREADCRUMBS -->

<!-- SHOP BLOCK -->
<section class="shop" style="padding-top: 2%">

    <!-- CONTAINER -->
    <div class="container">

        <!-- ROW -->
        <div class="row">

            <!-- SIDEBAR -->
            <div id="sidebar" class="col-lg-3 col-md-3 col-sm-3 padbot50">
                <div class="sidepanel widget_search">
                    <form class="search_form" action="javascript:void(0);" method="get" name="search_form">
                        <input  id="search_input" type="text" name="Search..." value="Search..." onfocus="if (this.value == 'Search...') this.value = '';" onblur="if (this.value == '') this.value = 'Search...';">
                    </form>
                </div>

                <!-- CATEGORIES -->
                <div class="sidepanel widget_categories">
                    <h3>Product Categories</h3>
                    <ul>
                        @foreach (souscategorie sc in ((List<souscategorie>) ViewBag.sCats))
                        {
                            <li><a href="@Url.Action("SubCategory", new {cat = @Request.QueryString["cat"], scat = @sc.Id})">@sc.Libelle</a></li>
                        }
                    </ul>
                </div><!-- //CATEGORIES -->
            
                

            </div><!-- //SIDEBAR -->
            <!-- SHOP PRODUCTS -->
            <div class="col-lg-9 col-sm-9 col-sm-9 padbot20">



                <!-- SORTING TOVAR PANEL -->
                <div class="sorting_options clearfix">

                    <!-- COUNT TOVAR ITEMS -->
                    <div class="count_tovar_items">
                        <p>Number Of Product</p>
                        <span>@Html.Raw(Model.Count)</span>
                    </div><!-- //COUNT TOVAR ITEMS -->
                    
                    <!-- PRODUC SIZE -->
                    <div id="toggle-sizes">
                        <a class="view_box active" href="javascript:void(0);"><i class="fa fa-th-large"></i></a>
                        <a class="view_full" href="javascript:void(0);"><i class="fa fa-th-list"></i></a>
                    </div><!-- //PRODUC SIZE -->
                </div><!-- //SORTING TOVAR PANEL -->
                <!-- ROW -->
                <div class="row shop_block" id="product_container">

                    
                </div><!-- //ROW -->

                <hr>

                <div class="clearfix">
                    

                    <a class="show_all_tovar" href="javascript:void(0);">show all</a>

                </div>

            </div><!-- //SHOP PRODUCTS -->
        </div><!-- //ROW -->
    </div><!-- //CONTAINER -->
</section><!-- //SHOP -->

@section scripts
{
    <script>


        $.ajax({
            url: '@Url.Action("RenderProducts", "Shop")',
            type: 'POST',
            data: {
                cat: '@Request.Params["cat"]',
                scat: '@Request.Params["scat"]'
            },
            success:function(data) {
                $('#product_container').html(data);
            }
        });
        $('#search_input').change(function () {
            $.ajax({
                url: '@Url.Action("RenderProducts", "Shop")',
                type: 'POST',
                data: {
                    cat: '@Request.Params["cat"]',
                    search: $('#search_input').val()
                },
                success: function (data) {
                    $('#product_container').html(data);
                }
            });
        });
    </script>
}