web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Index1()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Checkout()
        {
            return View();
        }

        public ActionResult Checkout2(string method)
        {
            return View();
        }
    }
}

web/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using domaine.entities;
using web.App_Start;

namespace web.Controllers
{
    public class PaymentController : Controller
    {
        [HttpPost]
        public String Index(string month, string year, string cvc, string number, string amount)
        {

          HttpWebRequest request = (HttpWebRequest)WebRequest.Create(Config.BANK);
            request.Method = "POST";
          
            request.Headers.Add("month",month.ToString());
            request.Headers.Add("year", year.ToString());
            request.Headers.Add("cvc", cvc.ToString());
            request.Headers.Add("number", number.ToString());
            request.Headers.Add("amount",Session["total"].ToString());


            using (var reader = new StreamReader(request.GetResponse().GetResponseStream(), Encoding.UTF8))
                {
                    string responseText = reader.ReadToEnd();
                System.Diagnostics.Debug.WriteLine("here");
                    return responseText;

                }
           
        }
    }
}

web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

web/Views/Home/Checkout.cshtml
@{
    ViewBag.Title = "Checkout";
    Layout = "~/Views/Shared/_Home.cshtml";
}
@section css
{
    <style>
        .checkout_nav li{
            width:33%
        }

        .payment_meth {
            padding-left: 15%;
            padding-right: 15%;
        }
    </style>
}

<section class="breadcrumb parallax margbot30"></section>
<!-- //BREADCRUMBS -->
<!-- PAGE HEADER -->
<section class="page_header">

    <!-- CONTAINER -->
    <div class="container border0 margbot0">
        <h3 class="pull-left"><b>Checkout</b></h3>

    </div><!-- //CONTAINER -->
</section><!-- //PAGE HEADER -->
<!-- CHECKOUT PAGE -->
<section class="checkout_page">

    <!-- CONTAINER -->
    <div class="container">
        <!-- CHECKOUT BLOCK -->
        <div class="checkout_block">
            <ul class="checkout_nav">
                <li class="active_step">1. Payment method</li>
                <li>2. Paiement</li>
                <li>3. Order confirmation</li>
                
            </ul>

           
            <div class="checkout_form">
                <div class="payment_meth center-block btn-group-vertical" role="group" aria-label="blabla">
                    <form action="@Url.Action("Checkout2")" method="get">
                        
                   
                    <button name="method" type="submit" value="card" type="button" class="btn btn-primary">Credit card</button>
                    <button name="method" type="submit" value="balance" type="button" class="btn btn-default">Account balance</button>
                    </form>

                </div>
            </div>
        </div><!-- //CHECKOUT BLOCK -->
    </div><!-- //CONTAINER -->
</section><!-- //CHECKOUT PAGE -->

web/Views/Home/Checkout2.cshtml
@{ ViewBag.Title = "Checkout2"; Layout = "~/Views/Shared/_Home.cshtml";
} @section css{
      <style>
          .checkout_nav li {
              width: 33%;
          }


      </style>
<link href="~/Content/css/toastr.min.css" rel="stylesheet" />


  }

<section class="breadcrumb parallax margbot30"></section>
<!-- //BREADCRUMBS -->
<!-- PAGE HEADER -->
<section class="page_header">
    <!-- CONTAINER -->
    <div class="container border0 margbot0">
        <h3 class="pull-left">
            <b> Checkout</b>
        </h3>
    </div>
    <!-- //CONTAINER -->
</section>
<!-- //PAGE HEADER -->
<!-- CHECKOUT PAGE -->
<section class="checkout_page">
    <!-- CONTAINER -->
    <div class="container">
        <!-- CHECKOUT BLOCK -->
        <div class="checkout_block">
            <ul class="checkout_nav">
                <li class="done_step">1. Payment method</li>
                <li class="active_step">2. Paiement</li>
                <li>3. Order confirmation</li>
            </ul>
            <div class="checkout_form">
                <div class="payment_meth center-block btn-group-vertical"
                     role="group" aria-label="blabla">
                    <div class="row">
                        <div class="col-xs-12 col-md-8 col-md-offset-2">
                            <div class="form-group">
                                <label for="cardNumber"> CARD NUMBER </label>
                                 <input type="text" class="credit_card_number_form" id="cardNumber"
                                                                                     placeholder="Valid Card Number" requiredautofocus / >
                            </div>
                            <div class="row">
                                <div class="col-xs-7 col-md-7">
                                    <div class="form-group">
                                        <label for="expityMonth"> EXPIRY DATE </label>
                                        <div class="col-xs-6 col-lg-6 pl-ziro">
                                            <input type="text" class="credit_card_number_form"
                                                   id="expityMonth" id="month" placeholder="MM" required / >
                                        </div>
                                        <div class="col-xs-6 col-lg-6 pl-ziro">
                                            <input type="text" id="year" class="credit_card_number_form"
                                                   id="expityYear" placeholder="YY" required / >
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xs-5 col-md-5 pull-right">
                                    <div class="form-group">
                                        <label for="cvCode"> CV CODE </label> <input id="cvc"type="password"
                                                                                     class="credit_card_number_form" id="cvCode" placeholder="CV" required / >
                                    </div>
                                </div>
                            </div>
                            <br/ > <button id="pay"
                                      class="btn btn-success btn-lg btn-block" role="button">Pay</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- //CHECKOUT BLOCK -->
    </div>
    <!-- //CONTAINER -->
</section>
@section scripts
{
    <script src="~/Content/js/toastr.min.js"></script>

    <script>
        
        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-bottom-full-width",
            "preventDuplicates": true,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }


        $('#pay').on('click',
            function () {
                alert('click');
                $.ajax({
                    type:'POST',
                    url: '@Url.Action("Index","Payment")',
                    data: {
                        month: $('#month').val(),
                        year: $('#year').val(),
                        cvc: $('#cvc').val(),
                        number: $('#cardNumber').val(),

                    },
                    success: function (data) {
                        response = JSON.parse(data);
                        if (response.Code == 0) {
                            toastr["success"]("Payment validated");
                        } else {
                            toastr["error"](response.Message);
                        }
                    }
                });
            });
    </script>
}

web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Home.cshtml";
}

<!-- SCHOOL SALE -->
<section class="school_sale parallax margbot30">

    <!-- CONTAINER -->
    <div class="container">
        <div class="school_sale_description">
            <p>Skiing is a dance.</p>
            <span>discounts 30%</span>
        </div>
    </div><!-- //CONTAINER -->
</section><!-- //SCHOOL SALE -->
<!-- BANNER SECTION -->
<section class="banner_section">

    <!-- CONTAINER -->
    <div class="container" data-appear-top-offset='-100' data-animated='fadeInUp'>

        <!-- ROW -->
        <div class="row">
            <div class="top_sale_banners center">
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 col-ss-12"><a class="banner nobord margbot30" href="javascript:void(0);"><img src="~/Content/images/tovar/banner12.jpg" alt="" /></a></div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-ss-12"><a class="banner nobord margbot30" href="javascript:void(0);"><img src="~/Content/images/tovar/banner13.jpg" alt="" /></a></div>
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 col-ss-12"><a class="banner nobord margbot30" href="javascript:void(0);"><img src="~/Content/images/tovar/banner14.jpg" alt="" /></a></div>
            </div>
        </div><!-- //ROW -->
    </div><!-- //CONTAINER -->
</section><!-- //BANNER SECTION -->
<!-- NEW ARRIVALS -->
<section class="new_arrivals padbot50">

    <!-- CONTAINER -->
    <div class="container">
        <h2>new arrivals</h2>

        <!-- JCAROUSEL -->
        <div class="jcarousel-wrapper">

            <!-- NAVIGATION -->
            <div class="jCarousel_pagination">
                <a href="javascript:void(0);" class="jcarousel-control-prev"><i class="fa fa-angle-left"></i></a>
                <a href="javascript:void(0);" class="jcarousel-control-next"><i class="fa fa-angle-right"></i></a>
            </div><!-- //NAVIGATION -->

            <div class="jcarousel" data-appear-top-offset='-100' data-animated='fadeInUp'>
                <ul>
                    <li>
                        <!-- TOVAR -->
                        <div class="tovar_item_new">
                            <div class="tovar_img">
                                <img src="~/Content/images/tovar/children/new/1.jpg" alt="" />
                                <div class="open-project-link"><a class="open-project tovar_view" href="javascript:void(0);" data-url="%21projects/women/1.html">quick view</a></div>
                            </div>
                            <div class="tovar_description clearfix">
                                <a class="tovar_title" href="product-page.html">BABY ONE-PIECE IN RUGBY STRIPE</a>
                                <span class="tovar_price">$18.00</span>
                            </div>
                        </div><!-- //TOVAR -->
                    </li>
                    <li>
                        <!-- TOVAR -->
                        <div class="tovar_item_new">
                            <div class="tovar_img">
                                <img src="~/Content/images/tovar/children/new/2.jpg" alt="" />
                                <div class="open-project-link">
                                    <a class="open-project tovar_view" href="javascript:void(0);" data-url="%21projects/women/1.html">quick view</a>
                                </div>
                            </div>
                            <div class="tovar_description clearfix">
                                <a class="tovar_title" href="product-page.html">skirted one-piece in polka-dot heart</a>
                                <span class="tovar_price">$38.00</span>
                            </div>
                        </div><!-- //TOVAR -->
                    </li>
                    <li>
                        <!-- TOVAR -->
                        <div class="tovar_item_new">
                            <div class="tovar_img">
                                <img src="~/Content/images/tovar/children/new/3.jpg" alt="" />
                                <div class="open-project-link">
                                    <a class="open-project tovar_view" href="javascript:void(0);" data-url="%21projects/women/1.html">quick view</a>
                                </div>
                            </div>
                            <div class="tovar_description clearfix">
                                <a class="tovar_title" href="product-page.html">Baby one-piece in heart stripe</a>
                                <span class="tovar_price">$23.00</span>
                            </div>
                        </div><!-- //TOVAR -->
                    </li>
                    <li>
                        <!-- TOVAR -->
                        <div class="tovar_item_new">
                            <div class="tovar_img">
                                <img src="~/Content/images/tovar/children/new/4.jpg" alt="" />
                                <div class="open-project-link">
                                    <a class="open-project tovar_view" href="javascript:void(0);" data-url="%21projects/women/1.html">quick view</a>
                                </div>
                            </div>
                            <div class="tovar_description clearfix">
                                <a class="tovar_title" href="product-page.html">Baby one-piece in stripe</a>
                                <span class="tovar_price">$18.00</span>
                            </div>
                        </div><!-- //TOVAR -->
                    </li>
                    <li>
                        <!-- TOVAR -->
                        <div class="tovar_item_new">
                            <div class="tovar_img">
                                <img src="~/Content/images/tovar/children/new/5.jpg" alt="" />
                                <div class="open-project-link">
                                    <a class="open-project tovar_view" href="javascript:void(0);" data-url="%21projects/women/1.html">quick view</a>
                                </div>
                            </div>
                            <div class="tovar_description clearfix">
                                <a class="tovar_title" href="product-page.html">Baby polo one-piece</a>
                                <span class="tovar_price">$24.00</span>
                            </div>
                        </div><!-- //TOVAR -->
                    </li>
                    <li>
                        <!-- TOVAR -->
                        <div class="tovar_item_new">
                            <div class="tovar_img">
                                <img src="~/Content/images/tovar/children/new/6.jpg" alt="" />
                                <div class="open-project-link">
                                    <a class="open-project tovar_view" href="javascript:void(0);" data-url="%21projects/women/1.html">quick view</a>
                                </div>
                            </div>
                            <div class="tovar_description clearfix">
                                <a class="tovar_title" href="product-page.html">BOBO CHOSES BABY ONE-PIECE</a>
                                <span class="tovar_price">$22.00</span>
                            </div>
                        </div><!-- //TOVAR -->
                    </li>
                    <li>
                        <!-- TOVAR -->
                        <div class="tovar_item_new">
                            <div class="tovar_img">
                                <img src="~/Content/images/tovar/children/new/1.jpg" alt="" />
                                <div class="open-project-link"><a class="open-project tovar_view" href="javascript:void(0);" data-url="%21projects/women/1.html">quick view</a></div>
                            </div>
                            <div class="tovar_description clearfix">
                                <a class="tovar_title" href="product-page.html">BABY ONE-PIECE IN RUGBY STRIPE</a>
                                <span class="tovar_price">$18.00</span>
                            </div>
                        </div><!-- //TOVAR -->
                    </li>
                    <li>
                        <!-- TOVAR -->
                        <div class="tovar_item_new">
                            <div class="tovar_img">
                                <img src="~/Content/images/tovar/children/new/2.jpg" alt="" />
                                <div class="open-project-link">
                                    <a class="open-project tovar_view" href="javascript:void(0);" data-url="%21projects/women/1.html">quick view</a>
                                </div>
                            </div>
                            <div class="tovar_description clearfix">
                                <a class="tovar_title" href="product-page.html">skirted one-piece in polka-dot heart</a>
                                <span class="tovar_price">$38.00</span>
                            </div>
                        </div><!-- //TOVAR -->
                    </li>
                    <li>
                        <!-- TOVAR -->
                        <div class="tovar_item_new">
                            <div class="tovar_img">
                                <img src="~/Content/images/tovar/children/new/3.jpg" alt="" />
                                <div class="open-project-link">
                                    <a class="open-project tovar_view" href="javascript:void(0);" data-url="%21projects/women/1.html">quick view</a>
                                </div>
                            </div>
                            <div class="tovar_description clearfix">
                                <a class="tovar_title" href="product-page.html">Baby one-piece in heart stripe</a>
                                <span class="tovar_price">$23.00</span>
                            </div>
                        </div><!-- //TOVAR -->
                    </li>
                    <li>
                        <!-- TOVAR -->
                        <div class="tovar_item_new">
                            <div class="tovar_img">
                                <img src="~/Content/images/tovar/children/new/4.jpg" alt="" />
                                <div class="open-project-link">
                                    <a class="open-project tovar_view" href="javascript:void(0);" data-url="%21projects/women/1.html">quick view</a>
                                </div>
                            </div>
                            <div class="tovar_description clearfix">
                                <a class="tovar_title" href="product-page.html">Baby one-piece in stripe</a>
                                <span class="tovar_price">$18.00</span>
                            </div>
                        </div><!-- //TOVAR -->
                    </li>
                </ul>
            </div>
        </div><!-- //JCAROUSEL -->
    </div><!-- //CONTAINER -->
</section><!-- //NEW ARRIVALS -->
<!-- BANNER SECTION -->
<section class="banner_section">

    <!-- CONTAINER -->
    <div class="container" data-appear-top-offset='-100' data-animated='fadeInUp'>

        <!-- ROW -->
        <div class="row">
            <div class="top_sale_banners center">
                <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7 col-ss-12"><a class="banner nobord margbot30" href="javascript:void(0);"><img src="~/Content/images/tovar/banner15.jpg" alt="" /></a></div>
                <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5 col-ss-12"><a class="banner nobord margbot30" href="javascript:void(0);"><img src="~/Content/images/tovar/banner16.jpg" alt="" /></a></div>
            </div>
        </div><!-- //ROW -->
    </div><!-- //CONTAINER -->
</section><!-- //BANNER SECTION -->
<!-- SERVICES SECTION -->
<section class="services_section padbot30">

    <!-- CONTAINER -->
    <div class="container" data-appear-top-offset='-100' data-animated='fadeInUp'>

        <!-- ROW -->
        <div class="row">

            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-ss-12 padbot30">
                <div class="service_item">
                    <div class="clearfix"><i class="fa fa-truck"></i><p>Free Shipping</p></div>
                    <span>Thundercats squid single-origin coffee YOLO selfies disrupt, master cleanse semiotics letterpress typewriter.</span>
                </div>
            </div>

            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-ss-12 padbot30">
                <div class="service_item">
                    <div class="clearfix"><i class="fa fa-gift"></i><p>Many Gifts</p></div>
                    <span>Thundercats squid single-origin coffee YOLO selfies disrupt, master cleanse semiotics letterpress typewriter.</span>
                </div>
            </div>

            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-ss-12 padbot30">
                <div class="service_item">
                    <div class="clearfix"><i class="fa fa-check-square-o"></i><p>Assistance in selecting</p></div>
                    <span>Thundercats squid single-origin coffee YOLO selfies disrupt, master cleanse semiotics letterpress typewriter.</span>
                </div>
            </div>

            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-ss-12 padbot30">
                <div class="service_item">
                    <div class="clearfix"><i class="fa fa-credit-card"></i><p>Gift card for Free</p></div>
                    <span>Thundercats squid single-origin coffee YOLO selfies disrupt, master cleanse semiotics letterpress typewriter.</span>
                </div>
            </div>
        </div><!-- //ROW -->
    </div><!-- //CONTAINER -->
</section><!-- //SERVICES SECTION -->