web/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using domaine.entities;
using Newtonsoft.Json;
using SpecificServices.services;
using web.Util;

namespace web.Controllers
{
    public class CartController : Controller
    {
        [HttpPost]
        public string Add(int id)
        {
            ProductService productService = new ProductService();
            product product = productService.GetById(id);
            if (product != null)
            {


                Dictionary<product, int> cart = (Dictionary<product, int>) Session["cart"];
                if (cart == null)
                    cart = new Dictionary<product, int>();

                if (cart.ContainsKey(product))
                {
                    cart[product]++;
                }

                else
                {
                    cart[product] = 1;
                }

                Session["cart"] = cart;

              
                 
              
               
                
                
                return JsonConvert.SerializeObject(new MessageResponse {Code=0,Message = "Product added to cart" });
                //return JsonConvert.SerializeObject(cart);
            }

            return JsonConvert.SerializeObject(new MessageResponse {Code = 1,Message = "Couldn't add product to card"});

        }

        public string Count()
        {
            Dictionary<product,int> cart = (Dictionary<product, int>) Session["cart"];
            if (cart == null)
            {
                return "0";
            }
            else
            {
                return cart.Count.ToString();
            }
        }

        public ActionResult Content()
        {
            Dictionary<product, int> cart = (Dictionary<product, int>)Session["cart"];
            ViewBag.cart = cart;
            return PartialView();
        }
    }

  
}

web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Index1()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Checkout()
        {
            return View();
        }

        public ActionResult Checkout2(string method)
        {
            return View();
        }
    }
}

web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using web.App_Start;
using web.Models;
using web.Util;

namespace web.Controllers
{
    public class UserController : Controller
    {
        public string BaseUrl = Config.URL+"users";
        // GET: User
        public ActionResult Login()
        {
            return View();

        }

       

        [HttpPost]
        public ActionResult Login(string login,string password)
        {
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(BaseUrl);
            request.Method = "POST";
            request.Headers.Add("login",login);
            request.Headers.Add("password",password);
            
            using (var reader = new StreamReader(request.GetResponse().GetResponseStream(), Encoding.UTF8))
            {
                string responseText = reader.ReadToEnd();
                LoginResponse response = JsonConvert.DeserializeObject<LoginResponse>(responseText);
                if (response.Code == 0)
                {
                    Session["user"] = response.Token.user;
                    Session["token"] = response.Token.value;
                    System.Diagnostics.Debug.WriteLine(response.Token.value);
                    return RedirectToAction("Index", "Home");
                }

                else
                {


                    return RedirectToAction("Login",new {message=response.Message});
                }    


            }

            

        }
    }
}

web/Views/Shared/_Home.cshtml
@using domaine.entities

@{
    ViewBag.Title = "_Home";
    user u = (user)Session["user"];
    
}

<!DOCTYPE html>
<html lang="en">
<!-- Mirrored from demo.evatheme.com/html/glammy/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 08 Nov 2017 12:23:40 GMT -->
<head>

    <meta charset="utf-8">
    <title>Skiing The World </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="eZraa">

    <!-- CSS -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/flexslider.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/fancySelect.css" rel="stylesheet" media="screen, projection" />
    <link href="~/Content/css/animate.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Content/css/style.css" rel="stylesheet" type="text/css" />

    <!-- FONTS -->
    <link href="~/Content/css/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    
    
    <style>
        #payModal {
            
        }
    </style>

    @RenderSection("css",required:false)

</head>
<body>
    <!-- PRELOADER -->
    <div id="preloader"><img src="~/Content/images/preloader.gif" /></div>
    <!-- //PRELOADER -->
    <div class="preloader_hide">
        <!-- PAGE -->
        <div id="page">

            <!-- HEADER -->
            <header>

                <!-- TOP INFO -->
                <div class="top_info">

                    <!-- CONTAINER -->
                    <div class="container clearfix">
                        <ul class="secondary_menu">
                            
                           @if (u == null)
                           {

                               <li><a href="my-account.html">Register</a></li>
                               <li><a href="@Url.Action("Login", "User")">Login</a></li>
                           }
                           else
                           {
                            <li><a href="#">My account</a></li>
                           }


                           
                          
                        </ul>

                        @if(u != null){
                            <div id="bClick" class="live_chat"><a href="javascript:void(0);"><i class="fa fa-money"></i> <div class="phone_top"></div><p id="balance">@Html.Raw(u.balance)</p> </a></div>
                        }

                    @{
                        if (u != null)
                        {
                            <div class="phone_top">Hello @Html.Raw(u.login) </div>
                        }
                    }
                        
                    </div><!-- //CONTAINER -->
                </div><!-- TOP INFO -->
                <!-- MENU BLOCK -->
                <div class="menu_block">

                    <!-- CONTAINER -->
                    <div class="container clearfix">

                        <!-- LOGO -->
                        <div class="logo">
                            <a href="@Url.Action("Index","Home")"><img src="~/Content/images/skilogo.png" alt="" style="max-width: 190%;" /></a>
                        </div><!-- //LOGO -->
                        <!-- SEARCH FORM -->
                        <div class="top_search_form">
                            <a class="top_search_btn" href="javascript:void(0);"><i class="fa fa-search"></i></a>
                            <form method="get" action="#">
                                <input type="text" name="search" value="Search" onFocus="if (this.value == 'Search') this.value = '';" onBlur="if (this.value == '') this.value = 'Search';" />
                            </form>
                        </div><!-- SEARCH FORM -->
                        <!-- SHOPPING BAG -->
                        <div class="shopping_bag">
                            <a class="shopping_bag_btn" href="javascript:void(0);"><i class="fa fa-shopping-cart"></i><p>shopping bag</p><span id="cart">2</span></a>
                            <div id="cart_holder" class="cart">
                               
                            </div>
                        </div><!-- //SHOPPING BAG -->
                        
                        <!-- MENU -->
                        <ul class="navmenu center">
                            <li class="sub-menu  @if(this.ViewContext.RouteData.Values["controller"].ToString().Equals("Home")){
                                                          @Html.Raw("active");
                                                      }">
                                <a href="@Url.Action("Index","Home")">Home</a>

                            </li>
                            <li class="sub-menu @if(this.ViewContext.RouteData.Values["controller"].ToString().Equals("Shop")){
                                                    @Html.Raw("active");
                                                }">
                                <a href="@Url.Action("Index","Shop")">Shop</a>
                                
                            </li>

                            <li class="sub-menu">
                                <a href="javascript:void(0);">Forum</a>
                            </li>
                            <li class="sub-menu">
                                <a href="javascript:void(0);">Blog</a>
                                <!-- MEGA MENU -->
                                <ul class="mega_menu megamenu_col1 clearfix">
                                    <li class="col">
                                        <ol>
                                            <li><a href="blog.html">Blog</a></li>
                                            <li><a href="blog-post.html">Blog Post</a></li>
                                        </ol>
                                    </li>
                                </ul><!-- //MEGA MENU -->
                            </li>
                        
                            <li class="sub-menu first @if(this.ViewContext.RouteData.Values["controller"].ToString().Equals("Revendeur")){
                                @Html.Raw("active");
                                }">
                                <a href="@Url.Action("AllSellers","Revendeur")">our sellers</a>

                            </li>

                        </ul><!-- //MENU -->
                    </div><!-- //MENU BLOCK -->
                </div><!-- //CONTAINER -->
            </header><!-- //HEADER -->
            <!--BODY-->
            @RenderBody()

            <!-- FOOTER -->
            <footer style="padding-top: 0" >
                <!-- CONTAINER -->
                <div class="container clearfix">
                    <div class="foot_logo" > <a href="@Url.Action("Index","Home")" ><img style="max-width: 170%" src="~/Content/images/foot_logo.png" alt="" /></a></div>
					
                    <div class="copyright_inf">
                        <span>SkiingTheWorld © 2017</span> |
                        <span>by CodeInc</span> |
                        <a class="back_top" href="javascript:void(0);" >Back to Top <i class="fa fa-angle-up"></i></a>
                    </div>
                </div><!-- //CONTAINER -->
            </footer><!-- //FOOTER -->
        </div><!-- //PAGE -->
    </div>
    <!-- TOVAR MODAL CONTENT -->
    <div id="modal-body" class="clearfix">
        <div id="tovar_content"></div>
        <div class="close_block"></div>
    </div><!-- TOVAR MODAL CONTENT -->
    <!-- SCRIPTS -->
    <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <!--[if IE]><html class="ie" lang="en"> <![endif]-->

    <script src="~/Scripts/js/jquery.min.js" type="text/javascript"></script>
    <script src="~/Scripts/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/Scripts/js/jquery.sticky.js" type="text/javascript"></script>
    <script src="~/Scripts/js/parallax.js" type="text/javascript"></script>
    <script src="~/Scripts/js/jquery.flexslider-min.js" type="text/javascript"></script>
    <script src="~/Scripts/js/jquery.jcarousel.js" type="text/javascript"></script>
    <script src="~/Scripts/js/fancySelect.js"></script>
    <script src="~/Scripts/js/animate.js" type="text/javascript"></script>
    <script src="~/Scripts/js/myscript.js" type="text/javascript"></script>
<script>
    if (top != self) top.location.replace(self.location.href);
</script>

<script>
    $(document).ready(function() {
        $('#bClick').on('click',
            function () {
                $('#payModal').modal('toggle');
            });


       
    });

    function getCartItemsCount() {
        console.log('count');
        $.ajax({
            url: '@Url.Action("Count","Cart")',
            
            type: 'GET',
            success: function (data) {
                console.log(data);
                $('#cart').html(data);
            }
        });

       
    }

    function renderCart() {
        console.log('render');
        $('#cart_holder').load('@Url.Action("Content","Cart")');
    }

  

    getCartItemsCount();
    renderCart();
    
    
</script>
    
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
@RenderSection("scripts",required:false)
    
    
    
    
</body>
<!-- Mirrored from demo.evatheme.com/html/glammy/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 08 Nov 2017 12:24:22 GMT -->
</html>

web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>