web/Controllers/RecharginCouponsController.cs
using System;
using System.Collections.Generic;
using System.IO;

using System.Net;

using System.Text;

using System.Web.Mvc;
using domaine.entities;
using Newtonsoft.Json;
using SpecificServices.services;
using web.App_Start;
using web.Util;

namespace web.Controllers
{
    public class RecharginCouponsController : Controller
    {
        public string BaseUrl = Config.URL+"secured/coupons";
        private user currentUser;

        // GET: RecharginCoupons
        public ActionResult Index()
        {
            List<recharging_coupon> coupons = new List<recharging_coupon>();
           

            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(BaseUrl);
            request.Method = "GET";
            currentUser = Session["user"] as user;
            request.Headers.Add("Authorization", Session["token"] as string);
           
            try
            {
               
                using (var reader = new StreamReader(request.GetResponse().GetResponseStream(), Encoding.UTF8))
                {
                    string responseText = reader.ReadToEnd();
                    coupons = Newtonsoft.Json.JsonConvert.DeserializeObject<List<recharging_coupon>>(responseText);
                    System.Diagnostics.Debug.WriteLine(coupons.Count);

                }
            }
            catch (Exception e)
            {
                return RedirectToAction("Error403", "Misc");
            }


                

                
                   
                
               
            
           




            return View(coupons);


        }

        // GET: RecharginCoupons/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RecharginCoupons/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RecharginCoupons/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RecharginCoupons/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RecharginCoupons/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

       

        // POST: RecharginCoupons/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult Generate(int count, double amount)
        {
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(BaseUrl);
            request.Method = "POST";
            request.Headers.Add("Authorization", Session["token"] as string);
            request.Headers.Add("count",count.ToString());
            request.Headers.Add("amount",amount.ToString());
            try
            {
                HttpWebResponse response = (HttpWebResponse) request.GetResponse();
            }
            catch (Exception e)
            {
                ModelState.AddModelError("Error", e.Message);
                return RedirectToAction("Index");
            }
           
            
                using (var reader = new StreamReader(request.GetResponse().GetResponseStream(), Encoding.UTF8))
                {
                    string responseText = reader.ReadToEnd();
                    MessageResponse res = JsonConvert.DeserializeObject<MessageResponse>(responseText);


                }
            
            
                
            


            return RedirectToAction("Index");
        }

        public ActionResult Generate()
        {
            return View();
        }

        public ActionResult Delete(int id)
        {
            RechargingCouponService s = new RechargingCouponService();
            recharging_coupon c = s.GetById(id);
            if (c == null)
                return new HttpNotFoundResult();
            s.Delete(s.GetById(id));
            s.Commit();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Pay(string code)
        {

            RechargingCouponService s = new RechargingCouponService();
            recharging_coupon c = s.getByCode(code);

            System.Diagnostics.Debug.WriteLine(code);
            if (c != null)
            {
                if (c.isUsed)
                {
                    ViewBag.Code = 1;
                    ViewBag.Message = "The coupon is used !";
                }
                else
                {
                    user u = (user) Session["user"];
                    if (u != null)
                    {
                        c.isUsed = true;
                        s.Update(c);
                        s.Commit();
                        UserService us = new UserService();
                        System.Diagnostics.Debug.WriteLine(code);

                        u = us.GetById(u.id);
                        u.balance += (double)c.amount;
                        us.Update(u);
                        us.Commit();
                        ViewBag.Code = 0;
                        ViewBag.Message = "Balance recharged !";
                    }
                }
            }
            else
            {
                ViewBag.Code = 1;
                ViewBag.Message = "The coupon is not valid !";
            }

            if (ViewBag.code != 0)
            {
                return RedirectToAction("Recharge", new {message = ViewBag.Message});
            }


            return RedirectToAction("Index", "Home");
        }

        public ActionResult Recharge()
        {
            return View();
        }
    }

    
}

web/Views/RecharginCoupons/Generate.cshtml
@model web.Models.AddCouponModel

@{
    ViewBag.Title = "Generate";
    Layout = "~/Views/Shared/_BackOffice.cshtml";
}

@section title{
    Generate new coupons
}
<form action="@Url.Action("Generate","RecharginCoupons")" method="post">
    <div class="row">

        <div class="col-md-10 col-md-offset-1 text-center">
            <div class="col-md-5">
                <h3>Number of coupons</h3>
                <input class="knob" name="count" />
            </div>

            <div class="col-md-5">
                <h3>Amount</h3>
                <input class="knob" name="amount" />
            </div>
        </div>
        <br/>
        <div style="text-align: right" class="center-block col-md-12 col-md-offset-2">
            <button  class="btn btn-success text-right" type="submit">Generate</button>
        </div>
        
    </div>
</form>

<div style="text-align: right" class="center-block col-md-12 col-md-offset-2">
    <button  class="btn btn-success text-right" type="submit">@Html.ActionLink("Back to List", "Index")</button>
</div>


@section scripts
{

    <script src="~/Content/knob/jquery.knob.js"></script>
}

web/Views/RecharginCoupons/Index.cshtml
@model IEnumerable<domaine.entities.recharging_coupon>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_BackOffice.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Generate New", "Generate")
</p>

<p>
    @Html.ValidationMessage("error");
</p>
<table class="table table-striped" id="dt">
    <tr>
        <th>
           Amount
        </th>
        <th>
            @Html.DisplayNameFor(model => model.code)
        </th>
        <th>
            Date generated
        </th>
        <th>
           Used
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dateGenerated)
        </td>
        <td>
           @if (item.isUsed)
           {
               <button class="btn btn-success"><i class="fa fa-check-circle" aria-hidden="true"></i></button>
           }
           else
           {
            <button class="btn btn-danger">
                <i class="fa fa-times-circle-o" aria-hidden="true"></i></button>
                }
</td>
        <td>
           
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>
   @section scripts
   {
       <script src="~/Content/dt/jquery.dataTables.js"></script>
       <script src="~/Content/dt/dataTables.bootstrap.min.js"></script>
       <script src="~/Content/dt/datatables.min.js"></script>
   }



<script>
    $(document).ready(function () {
        
        $('#dt').DataTable();
    });
</script>

web/Views/RecharginCoupons/Pay.cshtml
@{
    Layout = null;
}

@if (ViewBag.Code == 0)
{
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <strong>Success </strong>@ViewBag.Message
    </div>
}
else
{
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <strong>Success </strong>@ViewBag.Message
    </div>
}

web/Views/RecharginCoupons/Recharge.cshtml
@{
    ViewBag.Title = "Recharge";
    Layout = "~/Views/Shared/_Home.cshtml";
}

<section class="my_account parallax">
			
    <!-- CONTAINER -->
    <div class="container">
        <div class="my_account_block clearfix">
            <div class="login">
                <h2>Recharge my balance</h2>
                @if (Request.QueryString["message"] != null)
                {
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <strong>Coupon problem </strong>@Request.QueryString["message"]
                    </div>
                }
                <form class="login_form" action="@Url.Action("Pay","RecharginCoupons")" method="post">
                   
                    <input class="last" type="text" name="code" value="Coupon code" onFocus="if (this.value == 'Coupon code') this.value = '';" onBlur="if (this.value == '') this.value = 'Coupon code';" />
                    <div class="clearfix">
                      
                     
                    </div>
                    <div class="center"><input type="submit" value="Recharge"></div>
                </form>
            </div>
           
        </div>
    </div><!-- //CONTAINER -->
</section><!-- //PAGE 404 -->